# Generated by Django 4.2.30 on 2026-06-28 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='is_remote',
        ),
        migrations.AddField(
            model_name='job',
            name='ai_summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='job',
            name='employment_type',
            field=models.CharField(blank=True, default='Unknown', max_length=30),
        ),
        migrations.AddField(
            model_name='job',
            name='maximum_experience',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='minimum_experience',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='primary_role',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='job',
            name='secondary_roles',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='job',
            name='seniority',
            field=models.CharField(blank=True, default='Unknown', max_length=30),
        ),
        migrations.AddField(
            model_name='job',
            name='technologies',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='job',
            name='work_type',
            field=models.CharField(blank=True, default='Unknown', max_length=30),
        ),
    ]
