# Generated by Django 4.2.30 on 2026-07-03 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_remove_job_is_remote_job_ai_summary_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['primary_role'], name='jobs_job_primary_8a0ef6_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['company'], name='jobs_job_company_73ae7f_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['work_type'], name='jobs_job_work_ty_4ebff2_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['employment_type'], name='jobs_job_employm_743f88_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['posted_date'], name='jobs_job_posted__0a7770_idx'),
        ),
    ]
