# Generated by Django 4.2.30 on 2026-07-06 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_savejobs_savejobs_unique_save_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='savejobs',
            name='status',
            field=models.CharField(choices=[('saved', 'Saved'), ('applied', 'Applied'), ('interview', 'Interview'), ('offer', 'Offer'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='saved', max_length=20),
        ),
    ]
