# Generated by Django 4.2.30 on 2026-06-11 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='update_data',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='resume',
            old_name='upload_date',
            new_name='uploaded_at',
        ),
    ]
