# Generated by Django 4.2.30 on 2026-06-11 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0003_resumeanalysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeanalysis',
            name='found_skills',
            field=models.JSONField(default=list),
        ),
    ]
