# Generated by Django 4.2.30 on 2026-06-13 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0004_resumeanalysis_found_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumeanalysis',
            name='resume',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resume', to='resumes.resume'),
        ),
    ]
