# Generated by Django 4.2.30 on 2026-06-24 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0005_alter_resumeanalysis_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeanalysis',
            name='strengths',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='suggestions',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='weaknesses',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='resumeanalysis',
            name='summary',
            field=models.TextField(blank=True, default=''),
        ),
    ]
