# Generated by Django 4.2.30 on 2026-06-28 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0006_resumeanalysis_strengths_resumeanalysis_suggestions_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resumeanalysis',
            old_name='skills',
            new_name='secondary_roles',
        ),
        migrations.RemoveField(
            model_name='resumeanalysis',
            name='created_at',
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='experience',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='primary_role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='technologies',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='resumeanalysis',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resumeanalysis',
            name='summary',
            field=models.TextField(default=''),
        ),
    ]
