# Generated by Django 4.2.30 on 2026-08-02 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='seasion',
            new_name='session',
        ),
    ]
